name: Continuous Deployment
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.2.0
            
            - run: echo "Setting up NodeJs"
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: 16.x

            - run: npm install -g surge
            - run: echo "Deploying website"
            - run: surge ./ parcialdevops.surge.sh --token  c5542a766e9ace8ed12c68e03af2e968
          
            - run: echo "Please visit => student21N.surge.sh"
