name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install --global surge

    - name: Build and Deploy
      run: |
        echo -e "manueljesusmedinacepeda@gmail.com\nManuel2134" | surge login
        
        surge --project ./ --domain estudiante-m-n.surge.sh
