name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Instalar Surge.sh
        npm install --global surge

        # Iniciar sesión en Surge.sh
        echo -e "manueljesusmedinacepeda@gmail.com\nManuel2134" | surge login

        # Desplegar en Surge.sh
        surge --project ./ --domain estudiante-m-n.surge.sh
